availableSecrets:
  secretManager:
    - versionName: projects/trueflag-459814/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    secretEnv: ['GITHUB_TOKEN']
    args:
      - '-c'
      - |
        git clone https://$GITHUB_TOKEN@github.com/JavideJ/trueflag-etl.git
        cd trueflag-etl
        gcloud components install dataform --quiet
        gcloud dataform repositories workflow-invocations create \
          --repository="trueflag_repo \
          --region="europe-west1" \
          --release-config="release_config" \
          --project="trueflag-459814"

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/trueflag-459814/serviceAccounts/python@trueflag-459814.iam.gserviceaccount.com'

